swagger: '2.0'
info:
    title: Beasts API
    version: 1.0.0
consumes:
    - application/json
produces:
    - application/json
basePath: /v1
paths:
    /checkdb:
        get:
            operationId: beasts.checkdb
            tags:
                - Beasts
            summary: Check database connection
            responses:
                '200':
                    description: Successful
                    schema:
                        type: string
    /beast:
        get:
            operationId: beasts.all
            tags:
                - Beasts
            summary: Retrieve all of beasts
            responses:
                '200':
                    description: Successful
                    schema:
                        type: array
                        items:
                            properties:
                                name:
                                    type: string
                                desc:
                                    type: string
                                image:
                                    type: string
    /beast/{beast_id}:
        put:
            operationId: beasts.update
            tags:
                - Beasts
            summary: Update beast
            parameters:
                - name: beast_id
                  in: path
                  description: Id of the Beast to update
                  type: integer
                  required: True
                - name: beast
                  in: body
                  schema:
                    type: object
                    properties:
                      name:
                        type: string
                      desc:
                        type: string
                      image:
                        type: string
            responses:
                200:
                    description: Successfully update Beast information
                    schema:
                        properties:
                            id:
                                type: string
                            name:
                                type: string
                            desc:
                                type: string
                            image:
                                type: string
                            create_timestamp:
                                type: string
