swagger: '2.0'
info:
    title: Beasts API
    version: 1.0.0
consumes:
    - application/json
produces:
    - application/json
basePath: /v1

paths:
    /beast:
        get:
            operationId: beasts.all
            tags:
                - Beasts
            summary: Retrieve all of beasts
            responses:
                '200':
                    description: Successful
                    schema:
                        type: array
                        items:
                            properties:
                                name:
                                    type: string
                                desc:
                                    type: string
                                image:
                                    type: string